<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>try ... catch</title>
    <script type="text/javascript">
    ///////////////////
    // try ... catch //
    ///////////////////

    function ranInt(max, min) {
        return parseInt(Math.random() * (max - min + 1) + min)
    }

    var errorArr = [new Error("错误"), new EvalError("错误"), new RangeError("超出范围"), new ReferenceError("无效引用"), new SyntaxError("语法错误"), new TypeError("参数错误")];

    var min = 0;
    var max = errorArr.length;

    try {
        throw errorArr[ranInt(max, min)]
    } catch (e) {
        if (e instanceof TypeError) {
            // statements to handle TypeError exceptions
            console.error("TypeError")
        } else if (e instanceof RangeError) {
            // statements to handle RangeError exceptions
            console.error("RangeError")
        } else if (e instanceof EvalError) {
            // statements to handle EvalError exceptions
            console.error("EvalError")
        } else {
            // statements to handle any unspecified exceptions
            console.error("其他错误"); // pass exception object to error handler
        }
    } finally {
        console.log("都会执行");
    }

    //



    try {
        try {
            throw new Error("oops");
        } finally {
            console.log("内部", "finally");
        }
    } catch (error) {
        console.error("外边", error.message);
    } finally {
        console.log("外边", "finally");
    }
    // finally
    // 外边 oops


    try {
        try {
            throw new Error("oops");
        } catch (error) {
            console.error("内部", error.message);
        } finally {
            console.log("内部", "finally");
        }
    } catch (error) {
        console.error("外边", error.message);
    } finally {
        console.log("外边", "finally");
    }
    // 内部 oops
    // finally



    try {
        fn();
        console.log("这里放的是正常的代码，就是你想执行的");
    } catch (err) {
        console.log("很不好彩，你以为理想的代码，由于某些原因发生了错误，就不走上面了，走这里" + "\n错误信息：" + err);
    } finally {
        console.log("无论出错与否都走这里");
    }


    /**
     * 实际上 try...catch应该尽可能少的使用，因为好多时候可以使用if去代替
     */
    if(typeof fn != "undefined" && typeof fn == "function"){
        fn();
    }else{
        console.log("没有这个 fn 函数");
    }

    // function fn(){console.log("fn 函数执行")};

    </script>
</head>

<body>
</body>

</html>